### ISSUE TITLE
Cannot get trade history for more then 5-6 days back

### ISSUE THREAD

**Issue by TreantBG** [bitshares/uptick#12]
I use this command and i cannot get any result that is older then 5-6 days from today

uptick trades BRIDGE.SMART:BRIDGE.BTC --start '2018-01-01 00:00:00' --stop '2018-01-03 00:00:00' 

is there something wrong with bitshares RPC?

**Comment by xeroc** [comment]
This is a backend limitation. Most public APIs only offer up to 100 (maybe 1000) entries in the account history. For that reason, people are currently working on elasticsearch integration for the backend
