### ISSUE TITLE
Uptick 0.1.9 error when using with python-bitshares 0.2.0

### ISSUE THREAD

**Issue by joelvai** [bitshares/uptick#13]
I get this error when trying to use `uptick --help`:

`    from bitshares.storage import configStorage as config
ImportError: cannot import name 'configStorage'
`

Seems to be just an import error, which was mentioned in the Bitshares 0.2.0 change log. Any plans on updating this soon?

> Instead of using
>  ```
> from bitshares.storage import configStorage as config
>  ```
>  use
>  ```
>  BitShares().config
>  ```
> or
> ```
> from bitshares.storage import get_default_config_store
>config = get_default_config_store()
> ```

**Comment by xeroc** [comment]
fixed with latest release
