### ISSUE TITLE
uptick transfer -- cannot add a memo

### ISSUE THREAD

**Issue by pramirez92** [bitshares/uptick#14]
This works:
uptick transfer someaccount 1.00 BTS 

This does not:
uptick transfer someaccount 1.00 BTS "some memo"

It seems to crap out here:
... wallet.py", line 171, in getPrivateKeyForPublicKey
bitshares.exceptions.KeyNotFound

I am using version 0.2.1. It was the same thing in 0.2.0

I really want to be able to include a memo. Much appreciated if you can fix this!

**Comment by xeroc** [comment]
That error usually means you do not have the private **memo** key which is required also when doing a transfer with a memo. New versions of pybitshares show the actualy key missing in the assert.
Also, `uptick permissions <account>` will show the distinct memo key too

**Comment by pramirez92** [comment]
That was it. Not sure how I missed that. Problem solved. Thank you!
