### ISSUE TITLE
Wallet doesn't accept empty password

### ISSUE THREAD

**Issue by ppitonak** [bitshares/uptick#2]
1. install uptick
2. `uptick addkey`... it will print "No wallet installed yet. Creating ... Wallet Encryption Passphrase:"
3. press <Enter>

result:
It prints "Wallet Encryption Passphrase:" again instead of accepting empty password which is not aligned with docs https://github.com/xeroc/uptick/blob/master/docs/common-calls.rst#adding-keys

The `changewalletpassphrase` behaves the same (I guess that it's the same function).

**Comment by xeroc** [comment]
That is intended behavior .. An empty wallet password is insecure

**Comment by ppitonak** [comment]
I completely agree with you that it's insecure but then you should update the docs because it's misleading... https://github.com/xeroc/uptick/blob/master/docs/common-calls.rst#adding-keys
