### ISSUE TITLE
new account error

### ISSUE THREAD

**Issue by guanqun** [bitshares/uptick#3]
I'm trying to use `uptick newaccount <my-account>` then I have following errors:

```
  File "/usr/local/lib/python3.4/site-packages/bitshares-0.1.8-py3.4.egg/bitshares/bitshares.py", line 302, in create_account
ValueError: Not registrar account given. Define it with registrar=x, or set the default_account using uptick
```

Not sure what this means...

**Comment by xeroc** [comment]
Read this:
http://docs.pybitshares.com/en/latest/bitshares.html#bitshares.bitshares.BitShares.create_account
