### ISSUE TITLE
Expires switch doesn't do anything

### ISSUE THREAD

**Issue by ppitonak** [bitshares/uptick#5]
```
uptick -d --expires 240 transfer myaccount 1 BTS
uptick -d -e 240 transfer myaccount 1 BTS
```
Both of these commands generate a transaction that expires in 30 seconds (default value according to docs).

**Comment by xeroc** [comment]
Thanks for the report. The option is passed right to the `BitShares` constructor which expected `expiration` instead of `expires`. I renamed the option and confirmed that it now works ..
